### ISSUE TITLE
Version unchanged

### ISSUE THREAD

**Issue by MMurarasu** [aso930/check_msa2040#2]
There is a major issue with this script. How come there were 494 commits, but the version of it is unchanged? This is not trustworthy for a production env. where we need to keep track of stuff added and audisting.

**Comment by aso930** [comment]
I see you're bored :)).

The internal version wasn't changed because there were no features added to it, only bug fixes. And those are reflected in the commit history.

**Comment by MMurarasu** [comment]
You sir, have a downvote and Unsubscribe following.
